import { Account, CSM } from './types';

export const TEAM: CSM[] = [
  { id: '1', name: 'Uchechukwu Precious', role: 'Customer Success Manager' },
  { id: '2', name: 'Marcus Chen', role: 'CSM' },
  { id: '3', name: 'Elena Rodriguez', role: 'CSM' },
  { id: '4', name: 'David Smith', role: 'CSM' },
  { id: '5', name: 'Priya Patel', role: 'CSM' },
];

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: 'stellar',
    name: 'Stellar Systems',
    description: 'Leading provider of aerospace manufacturing software and cloud components.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 8.4,
      csat: 4.8,
      healthScore: 92,
      ticketVolume: 3,
      openHighPriorityTickets: 0,
      lastQBRDate: '2026-02-15',
      isQBRMissed: false,
      productUsageScore: 85,
      engagementLevel: 'High',
      lastTouch: '2026-05-10',
      multiThreadingScore: 8,
      expansionPipeline: 50000,
      daysToRenewal: 240,
      strategicAlignment: 90,
    },
    interactions: [
      {
        id: 'i1',
        date: '2026-05-10',
        type: 'Weekly Sync',
        tone: '😊',
        tags: ['Product', 'Positive'],
        discussionPoints: 'Discussed Q3 roadmap and new feature adoption.',
        risks: 'None',
        opportunities: 'Interested in advanced analytics module.',
        nps: 9,
        notes: 'Client thrilled with new feature rollouts.',
        csmId: '1',
      },
      {
        id: 'i2',
        date: '2026-05-03',
        type: 'Ad-hoc Check-in',
        tone: '😐',
        tags: ['Risk'],
        discussionPoints: 'Integration timeline concerns.',
        risks: 'Q3 timeline might slip.',
        opportunities: 'Help from professional services.',
        nps: 7,
        notes: 'Concerned about Q3 integration timeline.',
        csmId: '1',
      }
    ],
    periodicNPS: [
      { id: 'p1', date: '2026-04-10', score: 9, period: 'Monthly' },
      { id: 'p2', date: '2026-03-10', score: 8, period: 'Monthly' },
      { id: 'p3', date: '2026-02-10', score: 8.5, period: 'Monthly' },
      { id: 'p4', date: '2026-01-10', score: 7, period: 'Monthly' }
    ]
  },
  {
    id: 'cloudnexus',
    name: 'CloudNexus',
    description: 'Global logistics firm specializing in cross-border e-commerce solutions.',
    status: 'At Risk',
    csmId: '1',
    metrics: {
      nps: 4.2,
      csat: 3.1,
      healthScore: 55,
      ticketVolume: 12,
      openHighPriorityTickets: 4,
      lastQBRDate: '2026-01-05',
      isQBRMissed: true,
      productUsageScore: 45,
      engagementLevel: 'Medium',
      lastTouch: '2026-05-08',
      multiThreadingScore: 2,
      expansionPipeline: 0,
      daysToRenewal: 45,
      strategicAlignment: 40,
    },
    interactions: [
      {
        id: 'cn1',
        date: '2026-05-08',
        type: 'Support Escalation',
        tone: '😡',
        tags: ['Bug', 'Urgent'],
        discussionPoints: 'API downtime affecting production.',
        risks: 'Competitor evaluation mentioned.',
        opportunities: 'None',
        nps: 2,
        notes: 'CTO is extremely frustrated with recent outages.',
        csmId: '1',
      }
    ],
    periodicNPS: [
      { id: 'p1cn', date: '2026-04-10', score: 5, period: 'Monthly' },
      { id: 'p2cn', date: '2026-03-10', score: 6, period: 'Monthly' }
    ]
  },
  {
    id: 'terrafoundry',
    name: 'TerraFoundry',
    description: 'Sustainable construction materials innovator for urban infrastructure.',
    status: 'At Risk',
    csmId: '1',
    metrics: {
      nps: 2.5,
      csat: 2.2,
      healthScore: 32,
      ticketVolume: 25,
      openHighPriorityTickets: 8,
      lastQBRDate: '2026-01-20',
      isQBRMissed: true,
      productUsageScore: 30,
      engagementLevel: 'Low',
      lastTouch: '2026-05-01',
      multiThreadingScore: 1,
      expansionPipeline: 0,
      daysToRenewal: 12,
      strategicAlignment: 20,
    },
    interactions: [
      {
        id: 'tf1',
        date: '2026-05-01',
        type: 'Ad-hoc Check-in',
        tone: '😟',
        tags: ['Churn Risk'],
        discussionPoints: 'Contract non-renewal warning.',
        risks: 'Budget cuts across the board.',
        opportunities: 'Downsizing plan.',
        nps: 3,
        notes: 'Main point of contact left the company without a handoff.',
        csmId: '1',
      }
    ],
    periodicNPS: []
  },
  {
    id: 'biopulse',
    name: 'BioPulse',
    description: 'Bio-tech research lab focusing on genetic sequencing at scale.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 9.1,
      csat: 4.9,
      healthScore: 98,
      ticketVolume: 1,
      openHighPriorityTickets: 0,
      lastQBRDate: '2026-04-10',
      isQBRMissed: false,
      productUsageScore: 95,
      engagementLevel: 'High',
      lastTouch: '2026-05-11',
      multiThreadingScore: 9,
      expansionPipeline: 120000,
      daysToRenewal: 310,
      strategicAlignment: 95,
    },
    interactions: [],
    periodicNPS: [
      { id: 'p1bp', date: '2026-05-01', score: 9.5, period: 'Monthly' },
      { id: 'p2bp', date: '2026-04-01', score: 9, period: 'Monthly' }
    ]
  },
  {
    id: 'dataflow',
    name: 'DataFlow Inc',
    description: 'Real-time data streaming and processing for financial institutions.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 7.8,
      csat: 4.5,
      healthScore: 88,
      ticketVolume: 5,
      openHighPriorityTickets: 1,
      lastQBRDate: '2026-03-22',
      isQBRMissed: false,
      productUsageScore: 82,
      engagementLevel: 'High',
      lastTouch: '2026-05-09',
      multiThreadingScore: 6,
      expansionPipeline: 25000,
      daysToRenewal: 180,
      strategicAlignment: 85,
    },
    interactions: [],
    periodicNPS: []
  },
  {
    id: 'zenith',
    name: 'Zenith Retail',
    description: 'Omni-channel retail platform for premium fashion brands.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 8.0,
      csat: 4.6,
      healthScore: 90,
      ticketVolume: 2,
      openHighPriorityTickets: 0,
      lastQBRDate: '2026-04-05',
      isQBRMissed: false,
      productUsageScore: 88,
      engagementLevel: 'High',
      lastTouch: '2026-05-12',
      multiThreadingScore: 7,
      expansionPipeline: 45000,
      daysToRenewal: 210,
      strategicAlignment: 92,
    },
    interactions: [],
    periodicNPS: []
  },
  {
    id: 'ironclad',
    name: 'IronClad Security',
    description: 'Cybersecurity firm specializing in perimeter defense and zero-trust.',
    status: 'At Risk',
    csmId: '2',
    metrics: {
      nps: 3.5,
      csat: 2.8,
      healthScore: 42,
      ticketVolume: 15,
      openHighPriorityTickets: 5,
      lastQBRDate: '2026-01-15',
      isQBRMissed: true,
      productUsageScore: 35,
      engagementLevel: 'Low',
      lastTouch: '2026-04-20',
      multiThreadingScore: 2,
      expansionPipeline: 0,
      daysToRenewal: 30,
      strategicAlignment: 30,
    },
    interactions: [],
    periodicNPS: []
  },
  {
    id: 'velocity',
    name: 'Velocity Ads',
    description: 'High-speed programmatic advertising and marketing technology.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 7.2,
      csat: 4.0,
      healthScore: 80,
      ticketVolume: 8,
      openHighPriorityTickets: 1,
      lastQBRDate: '2026-02-28',
      isQBRMissed: false,
      productUsageScore: 75,
      engagementLevel: 'Medium',
      lastTouch: '2026-05-05',
      multiThreadingScore: 5,
      expansionPipeline: 15000,
      daysToRenewal: 150,
      strategicAlignment: 70,
    },
    interactions: [],
    periodicNPS: []
  },
  {
    id: 'nebula',
    name: 'Nebula Labs',
    description: 'Quantum computing research and development for drug discovery.',
    status: 'Onboarding',
    csmId: '1',
    metrics: {
      nps: 0,
      csat: 0,
      healthScore: 100,
      ticketVolume: 0,
      openHighPriorityTickets: 0,
      lastQBRDate: '2026-05-20',
      isQBRMissed: false,
      productUsageScore: 10,
      engagementLevel: 'High',
      lastTouch: '2026-05-13',
      multiThreadingScore: 3,
      expansionPipeline: 5000,
      daysToRenewal: 365,
      strategicAlignment: 100,
    },
    interactions: [
      {
        id: 'nb1',
        date: '2026-05-13',
        type: 'Onboarding',
        tone: '😊',
        tags: ['Onboarding', 'Positive'],
        discussionPoints: 'Kickoff call completed. Goals aligned.',
        risks: 'None',
        opportunities: 'Custom implementation needed.',
        nps: 0,
        notes: 'Client is eager to start. Implementation team assigned.',
        csmId: '1',
      }
    ],
    periodicNPS: []
  },
  {
    id: 'quantum',
    name: 'Quantum Optics',
    description: 'Next-generation optical networking for massive scale data centers.',
    status: 'Healthy',
    csmId: '1',
    metrics: {
      nps: 8.5,
      csat: 4.7,
      healthScore: 94,
      ticketVolume: 2,
      openHighPriorityTickets: 0,
      lastQBRDate: '2026-03-30',
      isQBRMissed: false,
      productUsageScore: 92,
      engagementLevel: 'High',
      lastTouch: '2026-05-11',
      multiThreadingScore: 8,
      expansionPipeline: 80000,
      daysToRenewal: 280,
      strategicAlignment: 96,
    },
    interactions: [],
    periodicNPS: []
  }
];
